# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-10 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_date',
            new_name='pubdate',
        ),
    ]
