# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-10 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20210810_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pubdate',
            new_name='pub_date',
        ),
    ]
