# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-08-09 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('author', models.CharField(max_length=32)),
                ('publish', models.CharField(max_length=32)),
            ],
        ),
    ]
